### PR TITLE
claimTokens func added to BaseCrowdsale.sol

### PR DESCRIPTION
**Pull request by ggs134**
Tests are not implememted.
This pull request related to #11

### CODE REVIEW

**Comment by thomashin** [comment]
this line is dangerous, because tokenOwner can be anyone.
https://github.com/ggs134/tokyo/blob/e95ce7d87c3a5b0b2ca54b3bd5cfecb5b8498c77/packages/tokyo-reusable-crowdsale/contracts/crowdsale/BaseCrowdsale.sol#L125

I think, It seems better to send the claimed erc20 to the owner and process it later like this.
https://github.com/OpenZeppelin/zeppelin-solidity/blob/a7e91856f3e275668b4a4c55cbd14864aa61b100/contracts/ownership/CanReclaimToken.sol

```javascript
function claimTokens(ERC20Basic token) external onlyOwner {
    require(isFinalized);
    uint256 balance = token.balanceOf(this);
    token.transfer(owner, balance);
}
```

**Comment by 4000D** [comment]
you may check [Contributing guide](https://github.com/Onther-Tech/tokyo/blob/master/CONTRIBUTING.md)

**Comment by 4000D** [comment]
Because only owner can `claimTokens`, it is assumed that token owner is known address for the _contract owner_.

But we need to take care which interface should we use for claiming.

**Comment by 4000D** [comment]
replaced with #12

**Pull request closed without merging**
